#!/bin/bash
set -euo pipefail


OUTPUT_FILE="${1:-dump.sql}"

{
    # Disable triggers so that data dump can be restored exactly as it is
    echo "SET session_replication_role = replica;
    "

    # Explanation of pg_dump flags:
    #
    #   --exclude-schema omit data from internal schemas as they are maintained by platform
    #   --exclude-table  omit data from migration history tables as they are managed by platform
    #   --column-inserts only column insert syntax is supported, ie. no copy from stdin
    #   --schema '*'     include all other schemas by default
    #
    # Explanation of sed substitutions:
    #
    #   - do not emit psql meta commands
    #
    # Never delete SQL comments because multiline records may begin with them.
    pg_dump \
        -d "$DB_URL" \
        --data-only \
        --quote-all-identifier \
        --role "postgres" \
        --exclude-schema "information_schema|pg_*|graphql|graphql_public|pgsodium|pgsodium_masks|pgtle|repack|tiger|tiger_data|timescaledb_*|_timescaledb_*|topology|vault|etl|extensions|pgbouncer|realtime|supabase_migrations|_analytics|_realtime|_supavisor" \
        --exclude-table "auth.schema_migrations" \
        --exclude-table "storage.migrations" \
        --exclude-table "supabase_functions.migrations" \
        --schema "*" \
        \
    | sed -E 's/^\\(un)?restrict .*$/-- &/'

    # Reset session config generated by pg_dump
    echo "RESET ALL;"
} > "$OUTPUT_FILE"

echo "Dump written to: $OUTPUT_FILE"

