#!/bin/bash
set -euo pipefail

OUTPUT_FILE="${1:-dump.sql}"

{
    # Explanation of pg_dumpall flags:
    #
    #   --roles-only     only include create, alter, and grant role statements
    #
    # Explanation of sed substitutions:
    #
    #   - do not emit psql meta commands
    #   - do not create or alter reserved roles as they are blocked by supautils
    #   - explicitly allow altering safe attributes, ie. statement_timeout, pgrst.*
    #   - discard role attributes that require superuser, ie. nosuperuser, noreplication
    #   - do not alter membership grants by supabase_admin role
    pg_dumpall \
        -d "$DB_URL" \
        --roles-only \
        --role "postgres" \
        --quote-all-identifier \
        --no-role-passwords \
        --no-comments \
    | sed -E 's/^\\(un)?restrict .*$/-- &/' \
    | sed -E "s/^CREATE ROLE \"(anon|authenticated|authenticator|cli_login_.*|dashboard_user|pgbouncer|postgres|service_role|supabase_.*|pgsodium_keyholder|pgsodium_keyiduser|pgsodium_keymaker|pgtle_admin)\"/-- &/" \
    | sed -E "s/^ALTER ROLE \"(anon|authenticated|authenticator|cli_login_.*|dashboard_user|pgbouncer|postgres|service_role|supabase_.*|pgsodium_keyholder|pgsodium_keyiduser|pgsodium_keymaker|pgtle_admin)\"/-- &/" \
    | sed -E "s/ (NOSUPERUSER|NOREPLICATION)//g" \
    | sed -E "s/^-- (.* SET \"(pgaudit.*|pgrst.*|session_replication_role|statement_timeout|track_io_timing)\" .*)/\1/" \
    | sed -E "s/GRANT \".*\" TO \"(anon|authenticated|authenticator|cli_login_.*|dashboard_user|pgbouncer|postgres|service_role|supabase_.*|pgsodium_keyholder|pgsodium_keyiduser|pgsodium_keymaker|pgtle_admin)\"/-- &/" \
    | sed -E "/^--/d" \
    | uniq

    # Reset session config generated by pg_dump
    echo "RESET ALL;"
} > "$OUTPUT_FILE"

echo "Dump written to: $OUTPUT_FILE"

